language: python
python:
  - "3.3"
  - "3.4"
before_install:
  - "sudo apt-get -q update"
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
  - "sudo apt-get -yV install hddtemp hdparm"
script:
  - "coverage run --source=hddfancontrol setup.py test"
after_success:
  - "coveralls"
