dist: trusty
sudo: required
language: python
cache:
  pip: true
  directories:
    - $HOME/.cache/pypy
matrix:
  include:
    - python: "3.3"
    - python: "3.4"
    - python: "3.5"
    - python: "3.5-dev"
    - python: "3.6"
    - python: "3.6-dev"
    - python: "3.7-dev"
    - python: "pypy3"
      env: PYPY3_PYTHON_VERSION=3.5 PYPY3_VERSION=5.10.0 PYPY3_SHA256=d03f81f26e5e67d808569c5c69d56ceb007df78f7e36ab1c50da4d9096cebde0
  allow_failures:
    - python: "3.5-dev"
    - python: "3.6-dev"
    - python: "3.7-dev"
    - python: "pypy3"
  fast_finish: true
before_install:
  - "sudo apt-get -q update"
  - "if [ $TRAVIS_PYTHON_VERSION != 'pypy3' ]; then pip install -U pip; fi"
  - "if [ $TRAVIS_PYTHON_VERSION = 'pypy3' ]; then mkdir -p ~/.cache/pypy && echo $PYPY3_SHA256  ~/.cache/pypy/pypy$PYPY3_PYTHON_VERSION-$PYPY3_VERSION-linux_x86_64-portable.tar.bz2 | sha256sum --status -c || curl -f -L https://bitbucket.org/squeaky/portable-pypy/downloads/pypy$PYPY3_PYTHON_VERSION-$PYPY3_VERSION-linux_x86_64-portable.tar.bz2 > ~/.cache/pypy/pypy$PYPY3_PYTHON_VERSION-$PYPY3_VERSION-linux_x86_64-portable.tar.bz2; fi"
  - "if [ $TRAVIS_PYTHON_VERSION = 'pypy3' ]; then echo $PYPY3_SHA256  ~/.cache/pypy/pypy$PYPY3_PYTHON_VERSION-$PYPY3_VERSION-linux_x86_64-portable.tar.bz2 | sha256sum --status -c && tar -xjf ~/.cache/pypy/pypy$PYPY3_PYTHON_VERSION-$PYPY3_VERSION-linux_x86_64-portable.tar.bz2 -C ~ && deactivate && ~/pypy$PYPY3_PYTHON_VERSION-$PYPY3_VERSION-linux_x86_64-portable/bin/virtualenv-pypy ~/pypy3-venv && . ~/pypy3-venv/bin/activate; fi"
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
  - "sudo apt-get -V install hddtemp hdparm"
script:
  - "coverage run --source=hddfancontrol setup.py test"
after_success:
  - "coveralls"
deploy:
  provider: pypi
  user: desbma
  password:
    secure: "LvuYMb0oHhZ74I7Kmd7AHSF4KXEGIS7NIz5bjIM7GeQJoq+2pqPbGvauk+xedXGnmLC7OFmhx9/TwciYKYnhtLepNFv09zi/h1G0YFUWRs87DdP3sbnr+1toeEGsYN7mYUg8EnAnQntjzYvWYQbbzb6Sm7o8GV32p4AkXle6Z1s="
  on:
    tags: true
    branch: master
    python: "3.6"
notifications:
  email:
    recipients:
      - secure: "GcRFeCAsuHdhSO6/S7fJRfuvkLXyDoFaZ7hkEGLwclx/zkD0puXxtoh5uqp5VZy2qOe8hSvkA9lhNUrJu7MAIjBPvuiYg9q1TgDU10xHb7850iJWRCVFiAlhs/dpOjpoXtaYmj7erCHg+ComYZ7nj/ICMZt/qxBCYEyW4G5vWCA="
    on_success: always
    on_failure: always
