[package]
name = "hddfancontrol"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.79", default-features = false, features = ["std", "backtrace"] }
clap = { version = "4.4.18", default-features = false, features = ["std", "color", "help", "usage", "error-context", "suggestions", "derive"] }
clap-num = { version = "1.1.1", default-features = false }
humantime = { version = "2.1.0", default-features = false }
log = { version = "0.4.20", default-features = false, features = ["max_level_trace", "release_max_level_debug"] }
simple_logger = { version = "4.3.3", default-features = false, features = ["colors", "stderr"] }
